# Generated by Django 2.2.7 on 2019-11-28 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_choice_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
